RestartCMD:
  - "save-all"

restarts:
  - 'Понедельник;00;00'
  - 'Понедельник;12;00'
  - 'Вторник;00;00'
  - 'Вторник;12;00'
  - 'Среда;00;00'
  - 'Среда;12;00'
  - 'Четверг;00;00'
  - 'Четверг;12;00'
  - 'Пятница;00;00'
  - 'Пятница;12;00'
  - 'Суббота;00;00'
  - 'Суббота;12;00'
  - 'Воскресенье;00;00'
  - 'Воскресенье;12;00'
  #- 'Ежедневно;00;00'

TitleAtIntervals:
  - 300
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

soundAtIntervals:
  - 300
  - 60
  - 30
  - 20
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

settings:
  sound: 'UI_BUTTON_CLICK'
  restart_delay_seconds: 3
  restart_cmd_offset: 15

vote:
  min_players: 10
  percentage: 70
  restart_time: 60
